# netlify.toml

[build]
  # 如果你的項目不需要構建步驟 (純靜態 + functions)，可以省略 publish
  # publish = "." # 假設你的 HTML/CSS/JS 文件在根目錄
  functions = "netlify/functions" # 指定 Netlify 函數目錄

# 配置 Edge Functions
[[edge_functions]]
  function = "inject-env"
  path = "/*"

# 配置重寫規則，將 /proxy/* 的請求路由到 proxy 函數
# 這樣前端的 PROXY_URL 仍然可以是 '/proxy/'
[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy/:splat" # 將路徑參數傳遞給函數
  status = 200 # 重要：這是代理，不是重定向

# 處理搜索路徑格式 /s=*
[[redirects]]
  from = "/s=*"
  to = "/index.html"
  status = 200

# （可選）為其他靜態文件設置緩存頭等
# [[headers]]
#   for = "/*"
#   [headers.values]
#     # Add any global headers here
